/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lotterySol from "./Lottery.sol";
export type { lotterySol };
export type { VRFv2Consumer } from "./VRFv2Consumer";
