/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as lotterySol from "./Lottery.sol";
export { VRFv2Consumer__factory } from "./VRFv2Consumer__factory";
